### PR TITLE
Added support for building docker containers on multiple distros, not…

### PR DESCRIPTION
**Pull request by dcrck**
… just Arch. find_distro.sh returns a string corresponding to your linux distro.

Also added a name to the local docker build: "autoroute-local"

### CODE REVIEW

**Comment by c00w** [comment]
Can we just use lsb_release -i? We're just changing the lib source.

Also you should confirm that every release you're adding uses glibc and not something different (copyright stuff).

**Comment by c00w** [comment]
Also feel free to go more aggresive and figure out how to get one of the build systems working (I.e. hashicorp's stuff, or docker compose).

**Comment by dcrck** [comment]
lsb_release is an optional package (on some distros). We could require it. As far as I know, Fedora/Redhat, Arch, Debian, and Ubuntu-based distributions of linux use glibc by defailt, so that should cover the most popular distributions. What's wrong with the current setup (build script + docker file)? Docker compose seems more focused on running multiple containers. That could be useful for testing, but we already have some architecture set up, I believe. What exactly do you want from the build / deployment system?

**Comment by c00w** [comment]
I'm not saying delete docker, I'm saying that rather than using this complicated find_distro.sh script, can we just do lsb_release -i and switch on that?

**Comment by dcrck** [comment]
Yes we could, if we also required users to have lsb_release, since it's an optional package on some distros. For now, though, I'll change it to use just lsb_release.

**Comment by c00w** [comment]
It's not users, just devs. So I'm not to worried about it.

**Comment by c00w** [comment]
Sorry for not merging this earlier, I didn't realize you had already simplified it. Feel free to poke me via text if I'm not on top of PR's. Or just poke eric.

**Pull request merged**
