### PR TITLE
Refactor network_sim_test to reduce duplication.

### PR DESCRIPTION
**Pull request by djpetti**
Now, code that both the test and loopback2 use to read the config
file lives in loopback2.

### CODE REVIEW

**Comment by c00w** [comment]
How did we manage to get the tests to 50% pass? That seems odd.

**Comment by c00w** [comment]
NVM failure is due to the loopback2 dependency.

**Comment by djpetti** [comment]
Sorry, hadn't rebased in too long...

**Comment by djpetti** [comment]
...aaaand forgot to run gofmt.

**Pull request merged**
